# Generated by Django 5.0.4 on 2024-09-28 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('political_organization', models.TextField()),
                ('degrees', models.TextField()),
                ('previous_jobs', models.TextField()),
                ('work_experience', models.TextField()),
                ('achivements', models.TextField()),
                ('vison', models.TextField()),
                ('goals', models.TextField()),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='uploads/profilePics')),
                ('votesCount', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VotingCountdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('mail', models.EmailField(max_length=254)),
                ('cwid', models.CharField(max_length=15)),
                ('otp', models.PositiveIntegerField(blank=True, null=True)),
                ('isVoted', models.BooleanField(default=False, null=True)),
                ('isVerified', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoterVotedTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.candidate')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voter')),
            ],
        ),
    ]
